//! Machine-generated artifacts (lock files, build output) must never
//! appear in `modified_files()` or `deleted_files()`. These files are
//! regenerated by the plan's finalize step; including them in a
//! changeset produces unnecessary merge conflicts between parallel
//! agents.

mod common;

use std::path::{Path, PathBuf};

use phantom_overlay::OverlayLayer;

use common::setup;

fn layer() -> OverlayLayer {
    let (lower, upper) = setup();
    // Leak the temp dirs for the test — dropping them deletes the backing
    // storage before we're done reading. The Box::leak is fine: the OS
    // cleans /tmp anyway at reboot and each test gets its own pair.
    let lower = Box::leak(Box::new(lower));
    let upper = Box::leak(Box::new(upper));
    OverlayLayer::new(lower.path().to_path_buf(), upper.path().to_path_buf()).unwrap()
}

#[test]
fn cargo_lock_at_root_excluded_from_modified_files() {
    let layer = layer();
    layer
        .write_file(Path::new("Cargo.lock"), b"# generated")
        .unwrap();
    layer
        .write_file(Path::new("src/main.rs"), b"fn main() {}")
        .unwrap();

    let modified = layer.modified_files().unwrap();
    assert!(
        modified.contains(&PathBuf::from("src/main.rs")),
        "source file should still be in modified_files"
    );
    assert!(
        !modified.contains(&PathBuf::from("Cargo.lock")),
        "Cargo.lock must be excluded from modified_files, got {modified:?}",
    );
}

#[test]
fn nested_cargo_lock_excluded() {
    let layer = layer();
    layer
        .write_file(Path::new("crates/foo/Cargo.lock"), b"# inner")
        .unwrap();
    let modified = layer.modified_files().unwrap();
    assert!(modified.is_empty(), "got {modified:?}");
}

#[test]
fn target_directory_excluded() {
    let layer = layer();
    layer
        .write_file(
            Path::new("target/debug/build/foo-1234/output"),
            b"build artifact",
        )
        .unwrap();
    layer.write_file(Path::new("src/lib.rs"), b"").unwrap();

    let modified = layer.modified_files().unwrap();
    assert_eq!(modified, vec![PathBuf::from("src/lib.rs")]);
}

#[test]
fn node_modules_excluded() {
    let layer = layer();
    layer
        .write_file(Path::new("node_modules/react/index.js"), b"module")
        .unwrap();
    layer
        .write_file(Path::new("package-lock.json"), b"{}")
        .unwrap();
    layer
        .write_file(Path::new("src/index.ts"), b"export {}")
        .unwrap();

    let modified = layer.modified_files().unwrap();
    assert_eq!(modified, vec![PathBuf::from("src/index.ts")]);
}

#[test]
fn python_caches_excluded() {
    let layer = layer();
    layer
        .write_file(Path::new("__pycache__/module.cpython-311.pyc"), b"bytecode")
        .unwrap();
    layer
        .write_file(Path::new(".pytest_cache/v/cache/nodeids"), b"[]")
        .unwrap();
    layer.write_file(Path::new("src/app.py"), b"").unwrap();

    let modified = layer.modified_files().unwrap();
    assert_eq!(modified, vec![PathBuf::from("src/app.py")]);
}

#[test]
fn deleted_cargo_lock_not_reported() {
    let (lower, upper) = setup();
    std::fs::write(lower.path().join("Cargo.lock"), b"# trunk").unwrap();

    let layer = OverlayLayer::new(lower.path().to_path_buf(), upper.path().to_path_buf()).unwrap();
    layer.delete_file(Path::new("Cargo.lock")).unwrap();

    let deleted = layer.deleted_files();
    assert!(
        !deleted.contains(&PathBuf::from("Cargo.lock")),
        "Cargo.lock deletion must not propagate as a changeset entry, got {deleted:?}",
    );
}

#[test]
fn source_files_not_excluded_even_when_named_like_directories() {
    // A source file in `crates/target/` (if a crate were named `target`)
    // is legitimate source, not build output — exclusion is anchored at
    // the first path component.
    let layer = layer();
    layer
        .write_file(Path::new("crates/target/src/lib.rs"), b"")
        .unwrap();

    let modified = layer.modified_files().unwrap();
    assert_eq!(modified, vec![PathBuf::from("crates/target/src/lib.rs")]);
}
