//! Machine-generated artifacts (lock files, build output) must never
//! appear in `modified_files()` or `deleted_files()`. These files are
//! regenerated by the plan's finalize step; including them in a
//! changeset produces unnecessary merge conflicts between parallel
//! agents.

mod common;

use std::path::{Path, PathBuf};

use phantom_overlay::OverlayLayer;

use common::setup;

fn layer() -> OverlayLayer {
    let (lower, upper) = setup();
    // Leak the temp dirs for the test — dropping them deletes the backing
    // storage before we're done reading. The Box::leak is fine: the OS
    // cleans /tmp anyway at reboot and each test gets its own pair.
    let lower = Box::leak(Box::new(lower));
    let upper = Box::leak(Box::new(upper));
    OverlayLayer::new(lower.path().to_path_buf(), upper.path().to_path_buf()).unwrap()
}

#[test]
fn cargo_lock_at_root_excluded_from_modified_files() {
    let layer = layer();
    layer
        .write_file(Path::new("Cargo.lock"), b"# generated")
        .unwrap();
    layer
        .write_file(Path::new("src/main.rs"), b"fn main() {}")
        .unwrap();

    let modified = layer.modified_files().unwrap();
    assert!(
        modified.contains(&PathBuf::from("src/main.rs")),
        "source file should still be in modified_files"
    );
    assert!(
        !modified.contains(&PathBuf::from("Cargo.lock")),
        "Cargo.lock must be excluded from modified_files, got {modified:?}",
    );
}

#[test]
fn nested_cargo_lock_excluded() {
    let layer = layer();
    layer
        .write_file(Path::new("crates/foo/Cargo.lock"), b"# inner")
        .unwrap();
    let modified = layer.modified_files().unwrap();
    assert!(modified.is_empty(), "got {modified:?}");
}

#[test]
fn target_directory_excluded() {
    let layer = layer();
    layer
        .write_file(
            Path::new("target/debug/build/foo-1234/output"),
            b"build artifact",
        )
        .unwrap();
    layer.write_file(Path::new("src/lib.rs"), b"").unwrap();

    let modified = layer.modified_files().unwrap();
    assert_eq!(modified, vec![PathBuf::from("src/lib.rs")]);
}

#[test]
fn node_modules_excluded() {
    let layer = layer();
    layer
        .write_file(Path::new("node_modules/react/index.js"), b"module")
        .unwrap();
    layer
        .write_file(Path::new("package-lock.json"), b"{}")
        .unwrap();
    layer
        .write_file(Path::new("src/index.ts"), b"export {}")
        .unwrap();

    let modified = layer.modified_files().unwrap();
    assert_eq!(modified, vec![PathBuf::from("src/index.ts")]);
}

#[test]
fn python_caches_excluded() {
    let layer = layer();
    layer
        .write_file(Path::new("__pycache__/module.cpython-311.pyc"), b"bytecode")
        .unwrap();
    layer
        .write_file(Path::new(".pytest_cache/v/cache/nodeids"), b"[]")
        .unwrap();
    layer.write_file(Path::new("src/app.py"), b"").unwrap();

    let modified = layer.modified_files().unwrap();
    assert_eq!(modified, vec![PathBuf::from("src/app.py")]);
}

#[test]
fn deleted_cargo_lock_not_reported() {
    let (lower, upper) = setup();
    std::fs::write(lower.path().join("Cargo.lock"), b"# trunk").unwrap();

    let layer = OverlayLayer::new(lower.path().to_path_buf(), upper.path().to_path_buf()).unwrap();
    layer.delete_file(Path::new("Cargo.lock")).unwrap();

    let deleted = layer.deleted_files();
    assert!(
        !deleted.contains(&PathBuf::from("Cargo.lock")),
        "Cargo.lock deletion must not propagate as a changeset entry, got {deleted:?}",
    );
}

#[test]
fn whiteouts_json_excluded_at_any_depth() {
    // Regression: an overlay teardown that interleaved writes could leave
    // `.whiteouts.json` files inside subdirectories. The previous filter
    // only caught the root copy, so nested ones leaked into changesets
    // and were observed in the wild at the repo root after materialization.
    //
    // Writes to `.whiteouts.json` are now rejected at the overlay write
    // boundary, so we seed the upper layer directly via std::fs to simulate
    // the corrupted state and verify the READ-SIDE filter still catches
    // nested copies.
    let (lower, upper) = setup();
    let upper_path = upper.path().to_path_buf();
    let layer = OverlayLayer::new(lower.path().to_path_buf(), upper_path.clone()).unwrap();

    std::fs::write(upper_path.join(".whiteouts.json"), b"{}").unwrap();
    std::fs::create_dir_all(upper_path.join("crates/foo")).unwrap();
    std::fs::write(upper_path.join("crates/foo/.whiteouts.json"), b"{}").unwrap();
    std::fs::create_dir_all(upper_path.join("src")).unwrap();
    std::fs::write(upper_path.join("src/main.rs"), b"fn main(){}").unwrap();

    let modified = layer.modified_files().unwrap();
    assert!(
        !modified
            .iter()
            .any(|p| p.file_name() == Some(std::ffi::OsStr::new(".whiteouts.json"))),
        ".whiteouts.json must be filtered out at every depth; got {modified:?}",
    );
    assert!(modified.contains(&PathBuf::from("src/main.rs")));
}

#[test]
fn dotgit_paths_never_appear_in_modified_files() {
    // A past bug let `.git/HEAD` from the overlay upper layer leak into a
    // changeset and be materialized back to trunk, wiping `.git/HEAD` and
    // `.git/config` and leaving the user's repo unopenable. The filter must
    // drop anything under `.git/` at any depth unconditionally — even if
    // it was seeded on disk outside `write_file`.
    let (lower, upper) = setup();
    let upper_path = upper.path().to_path_buf();
    let layer = OverlayLayer::new(lower.path().to_path_buf(), upper_path.clone()).unwrap();

    std::fs::create_dir_all(upper_path.join(".git/refs/heads")).unwrap();
    std::fs::write(upper_path.join(".git/HEAD"), b"ref: refs/heads/main\n").unwrap();
    std::fs::write(upper_path.join(".git/config"), b"[core]\n").unwrap();
    std::fs::write(upper_path.join(".git/refs/heads/main"), b"abc\n").unwrap();
    std::fs::create_dir_all(upper_path.join("src")).unwrap();
    std::fs::write(upper_path.join("src/main.rs"), b"fn main(){}").unwrap();

    let modified = layer.modified_files().unwrap();
    assert!(
        !modified
            .iter()
            .any(|p| p.starts_with(".git") || p.components().any(|c| c.as_os_str() == ".git")),
        ".git/* must never appear in modified_files; got {modified:?}",
    );
    assert!(modified.contains(&PathBuf::from("src/main.rs")));
}

#[test]
fn dotphantom_paths_never_appear_in_modified_files() {
    // `.phantom/` is Phantom's own state. Writing it back to trunk would
    // stomp the event DB and overlay registry.
    let (lower, upper) = setup();
    let upper_path = upper.path().to_path_buf();
    let layer = OverlayLayer::new(lower.path().to_path_buf(), upper_path.clone()).unwrap();

    std::fs::create_dir_all(upper_path.join(".phantom/overlays")).unwrap();
    std::fs::write(upper_path.join(".phantom/events.db"), b"").unwrap();
    std::fs::write(upper_path.join(".phantom/overlays/log"), b"").unwrap();
    std::fs::create_dir_all(upper_path.join("src")).unwrap();
    std::fs::write(upper_path.join("src/lib.rs"), b"").unwrap();

    let modified = layer.modified_files().unwrap();
    assert!(
        !modified.iter().any(
            |p| p.starts_with(".phantom") || p.components().any(|c| c.as_os_str() == ".phantom")
        ),
        ".phantom/* must never appear in modified_files; got {modified:?}",
    );
    assert!(modified.contains(&PathBuf::from("src/lib.rs")));
}

#[test]
fn dotgit_paths_never_appear_in_deleted_files() {
    // Whiting out `.git/HEAD` must not be visible to materialization. If it
    // reached the tree builder, materializer could attempt to delete a file
    // inside the trunk's `.git/` dir.
    let (lower, upper) = setup();
    let lower_path = lower.path().to_path_buf();
    std::fs::create_dir_all(lower_path.join(".git")).unwrap();
    std::fs::write(lower_path.join(".git/HEAD"), b"ref: refs/heads/main\n").unwrap();

    // Seed a pre-existing (pre-open) corrupted `.whiteouts.json` so the
    // layer loads an unsafe whiteout set and we can verify it is filtered
    // back out. This simulates an overlay that slipped past validation.
    std::fs::write(
        upper.path().join(".whiteouts.json"),
        r#"{"paths":[".git/HEAD",".phantom/events.db","src/real.rs"]}"#,
    )
    .unwrap();
    let lower_path = lower.path().to_path_buf();
    let layer = OverlayLayer::new(lower_path, upper.path().to_path_buf()).unwrap();

    let deleted = layer.deleted_files();
    for p in &deleted {
        assert!(
            !p.components().any(|c| c.as_os_str() == ".git"),
            ".git/* must never appear in deleted_files; got {deleted:?}"
        );
        assert!(
            !p.components().any(|c| c.as_os_str() == ".phantom"),
            ".phantom/* must never appear in deleted_files; got {deleted:?}"
        );
    }
}

#[test]
fn source_files_not_excluded_even_when_named_like_directories() {
    // A source file in `crates/target/` (if a crate were named `target`)
    // is legitimate source, not build output — exclusion is anchored at
    // the first path component.
    let layer = layer();
    layer
        .write_file(Path::new("crates/target/src/lib.rs"), b"")
        .unwrap();

    let modified = layer.modified_files().unwrap();
    assert_eq!(modified, vec![PathBuf::from("crates/target/src/lib.rs")]);
}
