//! Exclusion of machine-generated artifacts from changeset extraction.
//!
//! When parallel agents work on the same codebase, each typically runs
//! a build/test command that regenerates lock files (`Cargo.lock`,
//! `package-lock.json`, …) and produces build artifacts (`target/`,
//! `node_modules/`, …). If those files enter the changeset, every
//! agent in a wave collides on them at semantic-merge time even when
//! they edit entirely disjoint source files.
//!
//! Phantom elides these paths from `modified_files()` and
//! `deleted_files()`. Lock files are regenerated by the plan's
//! finalize step; build artifacts are ephemeral and never belong in
//! a changeset.

use std::path::Path;

use crate::types::first_component;

/// Basenames that are machine-generated and excluded at any depth.
///
/// Matches any path whose file name equals one of these — so
/// `Cargo.lock` at the root and `crates/foo/Cargo.lock` are both
/// excluded.
pub(crate) const EXCLUDED_BASENAMES: &[&str] = &[
    "Cargo.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "npm-shrinkwrap.json",
    "uv.lock",
    "poetry.lock",
    "Pipfile.lock",
    "go.sum",
    "composer.lock",
    "Gemfile.lock",
    "pubspec.lock",
];

/// Top-level directory names whose contents are machine-generated build
/// output and never belong in a changeset. Matched only at the first
/// path component to avoid accidentally excluding a source directory
/// that happens to share the name deeper in the tree.
pub(crate) const EXCLUDED_PREFIXES: &[&str] = &[
    "target",
    "node_modules",
    ".next",
    ".nuxt",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".dart_tool",
    ".svelte-kit",
    // `.claude/` holds per-agent Claude Code settings written by Phantom
    // (`phantom-session::hook_config`) so the running session can register
    // the trunk-update notification hooks in a directory Claude trusts.
    // Never belongs in a changeset.
    ".claude",
];

/// Returns `true` when the given relative path is a machine-generated
/// artifact that should be elided from changeset extraction.
pub(crate) fn is_excluded_artifact(rel_path: &Path) -> bool {
    if let Some(first) = first_component(rel_path)
        && EXCLUDED_PREFIXES.contains(&first)
    {
        return true;
    }
    if let Some(basename) = rel_path.file_name().and_then(|n| n.to_str())
        && EXCLUDED_BASENAMES.contains(&basename)
    {
        return true;
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn root_cargo_lock_excluded() {
        assert!(is_excluded_artifact(&PathBuf::from("Cargo.lock")));
    }

    #[test]
    fn nested_cargo_lock_excluded() {
        assert!(is_excluded_artifact(&PathBuf::from(
            "crates/foo/Cargo.lock"
        )));
    }

    #[test]
    fn package_lock_excluded() {
        assert!(is_excluded_artifact(&PathBuf::from("package-lock.json")));
        assert!(is_excluded_artifact(&PathBuf::from("pnpm-lock.yaml")));
    }

    #[test]
    fn target_dir_excluded() {
        assert!(is_excluded_artifact(&PathBuf::from(
            "target/debug/foo.rlib"
        )));
        assert!(is_excluded_artifact(&PathBuf::from("target")));
    }

    #[test]
    fn node_modules_excluded() {
        assert!(is_excluded_artifact(&PathBuf::from(
            "node_modules/react/index.js"
        )));
    }

    #[test]
    fn source_file_not_excluded() {
        assert!(!is_excluded_artifact(&PathBuf::from("src/main.rs")));
        assert!(!is_excluded_artifact(&PathBuf::from("Cargo.toml")));
        assert!(!is_excluded_artifact(&PathBuf::from("README.md")));
    }

    #[test]
    fn deep_non_prefix_match_not_excluded() {
        // `target` only matches as the FIRST component — a file at
        // `crates/target/src.rs` is source code, not build output.
        assert!(!is_excluded_artifact(&PathBuf::from(
            "crates/target/src.rs"
        )));
    }

    #[test]
    fn empty_path_not_excluded() {
        assert!(!is_excluded_artifact(&PathBuf::from("")));
    }
}
