//! Plan validation: cycle detection, wave (topological depth) computation,
//! and warning for file overlap between parallel domains.

use std::path::Path;

use phantom_core::plan::{Plan, PlanDomain};

/// Compute the wave (topological depth) for each domain.
/// Wave 0 = no dependencies, wave 1 = depends only on wave-0 domains, etc.
pub(super) fn compute_waves(domains: &[PlanDomain]) -> std::collections::HashMap<&str, usize> {
    use std::collections::HashMap;
    let mut waves: HashMap<&str, usize> = HashMap::new();

    // Iterative fixed-point: keep resolving until stable.
    loop {
        let mut changed = false;
        for domain in domains {
            let wave = if domain.depends_on.is_empty() {
                0
            } else {
                domain
                    .depends_on
                    .iter()
                    .map(|dep| waves.get(dep.as_str()).copied().unwrap_or(0) + 1)
                    .max()
                    .unwrap_or(0)
            };
            let prev = waves.insert(domain.name.as_str(), wave);
            if prev != Some(wave) {
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }

    waves
}

/// Validate that the dependency graph has no cycles.
///
/// Uses Kahn's algorithm (topological sort via in-degree counting).
/// Returns `Err` with a descriptive message if a cycle is found.
pub(super) fn validate_no_cycles(domains: &[PlanDomain]) -> anyhow::Result<()> {
    use std::collections::{HashMap, HashSet, VecDeque};

    let names: HashSet<&str> = domains.iter().map(|d| d.name.as_str()).collect();

    // Build adjacency list and in-degree counts.
    let mut in_degree: HashMap<&str, usize> = HashMap::new();
    let mut dependents: HashMap<&str, Vec<&str>> = HashMap::new();

    for domain in domains {
        in_degree.entry(domain.name.as_str()).or_insert(0);
        for dep in &domain.depends_on {
            if !names.contains(dep.as_str()) {
                anyhow::bail!(
                    "domain '{}' depends on '{}' which does not exist in the plan",
                    domain.name,
                    dep
                );
            }
            *in_degree.entry(domain.name.as_str()).or_insert(0) += 1;
            dependents
                .entry(dep.as_str())
                .or_default()
                .push(domain.name.as_str());
        }
    }

    // Process nodes with zero in-degree.
    let mut queue: VecDeque<&str> = in_degree
        .iter()
        .filter(|entry| *entry.1 == 0)
        .map(|entry| *entry.0)
        .collect();

    let mut processed = 0usize;

    while let Some(node) = queue.pop_front() {
        processed += 1;
        if let Some(deps) = dependents.get(node) {
            for &dependent in deps {
                if let Some(deg) = in_degree.get_mut(dependent) {
                    *deg -= 1;
                    if *deg == 0 {
                        queue.push_back(dependent);
                    }
                }
            }
        }
    }

    if processed < names.len() {
        let in_cycle: Vec<&str> = in_degree
            .iter()
            .filter(|entry| *entry.1 > 0)
            .map(|entry| *entry.0)
            .collect();
        anyhow::bail!(
            "dependency cycle detected among domains: {}",
            in_cycle.join(" -> ")
        );
    }

    Ok(())
}

/// Lock files that phantom's finalize step regenerates automatically — they
/// must never appear in a domain's `files_to_modify` scope.
const LOCK_FILE_BASENAMES: &[&str] = &[
    "Cargo.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "npm-shrinkwrap.json",
    "uv.lock",
    "poetry.lock",
    "Pipfile.lock",
    "go.sum",
    "composer.lock",
    "Gemfile.lock",
    "pubspec.lock",
];

/// Build-output directory prefixes that the overlay filters out of every
/// changeset — a planner that lists them is confused.
const ARTIFACT_PREFIXES: &[&str] = &[
    "target/",
    "node_modules/",
    ".next/",
    ".nuxt/",
    "__pycache__/",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".tox/",
    ".dart_tool/",
    ".svelte-kit/",
];

/// Warn when a plan lists files that phantom handles automatically.
///
/// - Lock files are regenerated by the finalize step.
/// - Build-artifact directories are filtered at submit time.
///
/// Listing either in `files_to_modify` indicates the planner did not follow
/// the prompt; the user is notified so they can revise the plan.
pub(super) fn warn_phantom_managed_paths(plan: &Plan) {
    for domain in &plan.domains {
        for file in &domain.files_to_modify {
            if let Some(basename) = file.file_name().and_then(|n| n.to_str())
                && LOCK_FILE_BASENAMES.contains(&basename)
            {
                crate::ui::warning_message(format!(
                    "domain '{}' lists lock file {} in files_to_modify — phantom regenerates lock files \
                     automatically; drop it from the scope",
                    console::style(&domain.name).bold(),
                    console::style(file.display()).bold(),
                ));
                continue;
            }
            let display = file.to_string_lossy();
            if ARTIFACT_PREFIXES
                .iter()
                .any(|prefix| display.starts_with(prefix))
            {
                crate::ui::warning_message(format!(
                    "domain '{}' lists build artifact {} in files_to_modify — artifacts are filtered at \
                     submit time; drop it from the scope",
                    console::style(&domain.name).bold(),
                    console::style(file.display()).bold(),
                ));
            }
        }
    }
}

/// Warn when the DAG has a wave with only one domain while a later wave has
/// two or more — the lone domain serializes the critical path and may be
/// splittable.
pub(super) fn warn_single_domain_bottlenecks(plan: &Plan) {
    use std::collections::HashMap;

    let waves = compute_waves(&plan.domains);
    let max_wave = waves.values().copied().max().unwrap_or(0);

    let mut wave_sizes: HashMap<usize, Vec<&str>> = HashMap::new();
    for domain in &plan.domains {
        let w = waves.get(domain.name.as_str()).copied().unwrap_or(0);
        wave_sizes.entry(w).or_default().push(&domain.name);
    }

    for wave in 0..=max_wave {
        let Some(members) = wave_sizes.get(&wave) else {
            continue;
        };
        if members.len() != 1 {
            continue;
        }
        // Only flag the lone domain if some later wave has a bigger fan-out —
        // a trailing single-domain wave (e.g. a finalize step) is expected.
        let has_wider_later_wave =
            (wave + 1..=max_wave).any(|w| wave_sizes.get(&w).is_some_and(|m| m.len() >= 2));
        if !has_wider_later_wave {
            continue;
        }
        crate::ui::warning_message(format!(
            "wave {wave} runs only one domain ('{}') while a later wave fans out — consider splitting it \
             into parallel subdomains to shorten the critical path",
            console::style(members[0]).bold(),
        ));
    }
}

/// Warn about files that appear in multiple domains within the same execution
/// wave. File overlap between parallel domains causes merge conflicts.
pub(super) fn warn_parallel_file_overlap(plan: &Plan) {
    use std::collections::HashMap;

    let waves = compute_waves(&plan.domains);
    let max_wave = waves.values().copied().max().unwrap_or(0);

    for wave in 0..=max_wave {
        // Collect files_to_modify per domain in this wave.
        let mut file_owners: HashMap<&Path, Vec<&str>> = HashMap::new();
        for domain in &plan.domains {
            if waves.get(domain.name.as_str()).copied().unwrap_or(0) != wave {
                continue;
            }
            for file in &domain.files_to_modify {
                file_owners
                    .entry(file.as_path())
                    .or_default()
                    .push(&domain.name);
            }
        }

        for (file, owners) in &file_owners {
            if owners.len() > 1 {
                crate::ui::warning_message(format!(
                    "{} is listed in files_to_modify by {} parallel domains in wave {}: {}",
                    console::style(file.display()).bold(),
                    owners.len(),
                    wave,
                    owners.join(", "),
                ));
                eprintln!(
                    "    {}",
                    console::style(
                        "This will likely cause a merge conflict. Consider adding depends_on \
                         between these domains."
                    )
                    .dim()
                );
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use phantom_core::id::PlanId;
    use phantom_core::plan::PlanStatus;

    fn domain(name: &str, depends_on: &[&str]) -> PlanDomain {
        domain_with_files(name, depends_on, &[])
    }

    fn domain_with_files(name: &str, depends_on: &[&str], files: &[&str]) -> PlanDomain {
        PlanDomain {
            name: name.into(),
            agent_id: format!("plan-test-{name}"),
            description: format!("test domain {name}"),
            files_to_modify: files.iter().map(std::path::PathBuf::from).collect(),
            files_not_to_modify: vec![],
            requirements: vec![],
            verification: vec![],
            depends_on: depends_on
                .iter()
                .map(std::string::ToString::to_string)
                .collect(),
            category: None,
        }
    }

    #[test]
    fn validate_no_cycles_accepts_valid_dag() {
        let domains = vec![
            domain("a", &[]),
            domain("b", &["a"]),
            domain("c", &["a", "b"]),
        ];
        assert!(validate_no_cycles(&domains).is_ok());
    }

    #[test]
    fn validate_no_cycles_accepts_independent_domains() {
        let domains = vec![domain("a", &[]), domain("b", &[]), domain("c", &[])];
        assert!(validate_no_cycles(&domains).is_ok());
    }

    #[test]
    fn validate_no_cycles_detects_direct_cycle() {
        let domains = vec![domain("a", &["b"]), domain("b", &["a"])];
        let err = validate_no_cycles(&domains).unwrap_err();
        assert!(err.to_string().contains("cycle"));
    }

    #[test]
    fn validate_no_cycles_detects_indirect_cycle() {
        let domains = vec![
            domain("a", &["c"]),
            domain("b", &["a"]),
            domain("c", &["b"]),
        ];
        let err = validate_no_cycles(&domains).unwrap_err();
        assert!(err.to_string().contains("cycle"));
    }

    #[test]
    fn validate_no_cycles_detects_self_cycle() {
        let domains = vec![domain("a", &["a"])];
        let err = validate_no_cycles(&domains).unwrap_err();
        assert!(err.to_string().contains("cycle"));
    }

    #[test]
    fn validate_no_cycles_detects_missing_dependency() {
        let domains = vec![domain("a", &["nonexistent"])];
        let err = validate_no_cycles(&domains).unwrap_err();
        assert!(err.to_string().contains("does not exist"));
    }

    #[test]
    fn validate_no_cycles_accepts_diamond_dag() {
        // a -> b, a -> c, b -> d, c -> d
        let domains = vec![
            domain("a", &[]),
            domain("b", &["a"]),
            domain("c", &["a"]),
            domain("d", &["b", "c"]),
        ];
        assert!(validate_no_cycles(&domains).is_ok());
    }

    #[test]
    fn compute_waves_independent_domains() {
        let domains = vec![domain("a", &[]), domain("b", &[])];
        let waves = compute_waves(&domains);
        assert_eq!(waves["a"], 0);
        assert_eq!(waves["b"], 0);
    }

    #[test]
    fn compute_waves_linear_chain() {
        let domains = vec![domain("a", &[]), domain("b", &["a"]), domain("c", &["b"])];
        let waves = compute_waves(&domains);
        assert_eq!(waves["a"], 0);
        assert_eq!(waves["b"], 1);
        assert_eq!(waves["c"], 2);
    }

    #[test]
    fn compute_waves_diamond() {
        let domains = vec![
            domain("a", &[]),
            domain("b", &["a"]),
            domain("c", &["a"]),
            domain("d", &["b", "c"]),
        ];
        let waves = compute_waves(&domains);
        assert_eq!(waves["a"], 0);
        assert_eq!(waves["b"], 1);
        assert_eq!(waves["c"], 1);
        assert_eq!(waves["d"], 2);
    }

    // warn_parallel_file_overlap prints to stderr and doesn't return a
    // testable value, so we extract the detection logic into a helper and
    // test that instead. The actual function calls this same logic.

    /// Detect overlapping files between parallel domains in the same wave.
    /// Returns (file, [domain_names]) for each overlap.
    fn detect_overlaps(plan: &Plan) -> Vec<(std::path::PathBuf, Vec<String>)> {
        use std::collections::HashMap;

        let waves = compute_waves(&plan.domains);
        let max_wave = waves.values().copied().max().unwrap_or(0);
        let mut results = Vec::new();

        for wave in 0..=max_wave {
            let mut file_owners: HashMap<&Path, Vec<&str>> = HashMap::new();
            for domain in &plan.domains {
                if waves.get(domain.name.as_str()).copied().unwrap_or(0) != wave {
                    continue;
                }
                for file in &domain.files_to_modify {
                    file_owners
                        .entry(file.as_path())
                        .or_default()
                        .push(&domain.name);
                }
            }
            for (file, owners) in file_owners {
                if owners.len() > 1 {
                    results.push((
                        file.to_path_buf(),
                        owners.into_iter().map(String::from).collect(),
                    ));
                }
            }
        }
        results
    }

    #[test]
    fn detects_overlap_in_same_wave() {
        let domains = vec![
            domain_with_files("scaffold", &[], &["package.json", "src/index.ts"]),
            domain_with_files("vim-engine", &[], &["package.json", "src/vim.ts"]),
        ];
        let plan = Plan {
            id: PlanId("test".into()),
            request: "test".into(),
            created_at: Utc::now(),
            domains,
            status: PlanStatus::Draft,
        };

        let overlaps = detect_overlaps(&plan);
        assert_eq!(overlaps.len(), 1);
        assert_eq!(overlaps[0].0, std::path::PathBuf::from("package.json"));
        assert_eq!(overlaps[0].1.len(), 2);
    }

    #[test]
    fn no_overlap_when_dependency_separates_waves() {
        let domains = vec![
            domain_with_files("scaffold", &[], &["package.json", "tsconfig.json"]),
            domain_with_files("vim-engine", &["scaffold"], &["package.json", "src/vim.ts"]),
        ];
        let plan = Plan {
            id: PlanId("test".into()),
            request: "test".into(),
            created_at: Utc::now(),
            domains,
            status: PlanStatus::Draft,
        };

        let overlaps = detect_overlaps(&plan);
        // package.json is in different waves (0 and 1), so no parallel overlap
        assert!(overlaps.is_empty());
    }

    #[test]
    fn no_overlap_when_files_disjoint() {
        let domains = vec![
            domain_with_files("api", &[], &["src/api.ts"]),
            domain_with_files("ui", &[], &["src/ui.ts"]),
        ];
        let plan = Plan {
            id: PlanId("test".into()),
            request: "test".into(),
            created_at: Utc::now(),
            domains,
            status: PlanStatus::Draft,
        };

        let overlaps = detect_overlaps(&plan);
        assert!(overlaps.is_empty());
    }

    /// `warn_phantom_managed_paths` and `warn_single_domain_bottlenecks`
    /// write to stderr. We test the underlying detection via local helpers
    /// that mirror the logic.
    fn detect_lock_file_claims(plan: &Plan) -> Vec<(String, std::path::PathBuf)> {
        let mut out = Vec::new();
        for domain in &plan.domains {
            for file in &domain.files_to_modify {
                if let Some(basename) = file.file_name().and_then(|n| n.to_str())
                    && LOCK_FILE_BASENAMES.contains(&basename)
                {
                    out.push((domain.name.clone(), file.clone()));
                }
            }
        }
        out
    }

    fn detect_single_domain_bottlenecks(plan: &Plan) -> Vec<usize> {
        use std::collections::HashMap;

        let waves = compute_waves(&plan.domains);
        let max_wave = waves.values().copied().max().unwrap_or(0);
        let mut wave_sizes: HashMap<usize, usize> = HashMap::new();
        for domain in &plan.domains {
            let w = waves.get(domain.name.as_str()).copied().unwrap_or(0);
            *wave_sizes.entry(w).or_insert(0) += 1;
        }
        (0..=max_wave)
            .filter(|w| wave_sizes.get(w).copied().unwrap_or(0) == 1)
            .filter(|w| (*w + 1..=max_wave).any(|l| wave_sizes.get(&l).copied().unwrap_or(0) >= 2))
            .collect()
    }

    fn plan_from(domains: Vec<PlanDomain>) -> Plan {
        Plan {
            id: PlanId("test".into()),
            request: "test".into(),
            created_at: Utc::now(),
            domains,
            status: PlanStatus::Draft,
        }
    }

    #[test]
    fn detects_cargo_lock_in_files_to_modify() {
        let plan = plan_from(vec![domain_with_files(
            "a",
            &[],
            &["Cargo.toml", "Cargo.lock"],
        )]);
        let claims = detect_lock_file_claims(&plan);
        assert_eq!(claims.len(), 1);
        assert_eq!(claims[0].0, "a");
        assert_eq!(claims[0].1, std::path::PathBuf::from("Cargo.lock"));
    }

    #[test]
    fn detects_nested_lock_file() {
        let plan = plan_from(vec![domain_with_files(
            "a",
            &[],
            &["crates/foo/Cargo.lock"],
        )]);
        let claims = detect_lock_file_claims(&plan);
        assert_eq!(claims.len(), 1);
    }

    #[test]
    fn ignores_non_lock_files() {
        let plan = plan_from(vec![domain_with_files(
            "a",
            &[],
            &["Cargo.toml", "src/main.rs"],
        )]);
        assert!(detect_lock_file_claims(&plan).is_empty());
    }

    #[test]
    fn detects_bottleneck_when_later_wave_fans_out() {
        // a (w0) -> b (w1) -> c, d (w2) — wave 1 is single, wave 2 fans out.
        let plan = plan_from(vec![
            domain("a", &[]),
            domain("b", &["a"]),
            domain("c", &["b"]),
            domain("d", &["b"]),
        ]);
        let bottlenecks = detect_single_domain_bottlenecks(&plan);
        assert_eq!(bottlenecks, vec![0, 1]);
    }

    #[test]
    fn does_not_flag_trailing_single_domain_wave() {
        // a (w0), b (w0) -> c (w1) — wave 1 is single but has no wider later wave.
        let plan = plan_from(vec![
            domain("a", &[]),
            domain("b", &[]),
            domain("c", &["a", "b"]),
        ]);
        let bottlenecks = detect_single_domain_bottlenecks(&plan);
        assert!(bottlenecks.is_empty());
    }

    #[test]
    fn does_not_flag_when_all_waves_are_wide() {
        let plan = plan_from(vec![
            domain("a", &[]),
            domain("b", &[]),
            domain("c", &["a"]),
            domain("d", &["b"]),
        ]);
        let bottlenecks = detect_single_domain_bottlenecks(&plan);
        assert!(bottlenecks.is_empty());
    }
}
